## Analyzing Virus Metadata Resource (VMR) Database
File: VMR_MSL41.v1.20260320.csv

Downloaded on: March 25, 2026

Url: https://ictv.global/vmr

In [6]:
import pandas as pd
import os

In [7]:
dataset_csv_filepath = os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/vmr/VMR_MSL41.v1.20260320.csv")

In [8]:
df = pd.read_csv(dataset_csv_filepath)

In [9]:
df.columns

Index(['Isolate ID', 'Species Sort', 'Isolate Sort', 'Realm', 'Subrealm',
       'Kingdom', 'Subkingdom', 'Phylum', 'Subphylum', 'Class', 'Subclass',
       'Order', 'Suborder', 'Family', 'Subfamily', 'Genus', 'Subgenus',
       'Species', 'ICTV_ID', 'Exemplar or additional isolate', 'Virus name(s)',
       'Virus name abbreviation(s)', 'Virus isolate designation',
       'Virus GENBANK accession', 'Genome coverage', 'Genome', 'Host source',
       'Accessions Link', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33'],
      dtype='object')

In [10]:
df

,Isolate ID,Species Sort,Isolate Sort,Realm,Subrealm,Kingdom,Subkingdom,Phylum,Subphylum,Class,...,Genome coverage,Genome,Host source,Accessions Link,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,VMR1028127,1,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
1,VMR1000002,2,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
2,VMR1000001,3,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Coding-complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
3,VMR1000003,4,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
4,VMR1000008,5,1,Adnaviria,NaN,Zilligvirae,NaN,Taleaviricota,NaN,Tokiviricetes,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19266,VMR1006179,17550,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Complete genome,ssDNA,plants,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
19267,VMR1006180,17551,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Complete genome,ssDNA,plants,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
19268,VMR1030577,17552,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
19269,VMR1030664,17553,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Complete genome,dsDNA,archaea,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN
19270,VMR1006181,17554,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Partial genome (non-compliant),dsDNA,protists,NCBI Nucleotide,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_1 = df[~df["Virus GENBANK accession"].isna()]
df_1.shape

(19130, 34)

In [18]:
df_1["Genome coverage"].value_counts()

Complete genome                   13866
Coding-complete genome             4669
Partial genome (non-compliant)      594
Name: Genome coverage, dtype: int64

In [22]:
df_2 = df_1[df_1["Genome coverage"] != "Partial genome (non-compliant)"]
df_2.shape

(18536, 34)

In [23]:
select_columns = ["Species", "Host source", "ICTV_ID", "Virus GENBANK accession"]
final_df = df_2[select_columns]
final_df

,Species,Host source,ICTV_ID,Virus GENBANK accession
0,Wargodvirus xiongnu,archaea,ICTV202420188,PP467602
1,Alphalipothrixvirus beppuense,archaea,ICTV201908643,MH447526
2,Alphalipothrixvirus umijigokuense,archaea,ICTV201908644,MK064563
3,Betalipothrixvirus acidiani,archaea,ICTV20094000,AM087120
4,Betalipothrixvirus hveragerdiense,archaea,ICTV20041365,AF440571
...,...,...,...,...
19265,Deltasatellite solani,plants,ICTV20165499,U74627
19266,Deltasatellite solaniflavusprimi,plants,ICTV20165500,JN819495
19267,Deltasatellite solaniflavussecundi,plants,ICTV20165501,KU232893
19268,Ispindelvirus danakilense,archaea,ICTV202522171,PQ827552
19269,Kodayamazakivirus kyodaii,archaea,ICTV202522258,HE580238

In [24]:
final_df.rename(columns={
    "Host source": "source_host_category",
    "Species": "source_virus_species_name",
    "ICTV_ID": "source_virus_species_ictvid",
    "Virus GENBANK accession": "ncbi_genbank_accession" 
}, inplace=True)

/tmp/ipykernel_4030595/198909324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.rename(columns={

In [25]:
final_df["dataset_source"] = "vmr"

/tmp/ipykernel_4030595/2459682159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["dataset_source"] = "vmr"

In [26]:
final_df.to_csv(os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/vmr/vmr_msl41v1_processed_20260327.csv"), index=False)